server:
  servlet:
    context-path: /api

spring:
  application:
    name: demo
  redis:
    database: 8
    host: 172.16.6.200
    password: 123456
  rabbitmq:
    host: 172.16.6.55
    port: 5672
    username: admin
    password: admin
#wx:
#  pay:
#    service:
#      provider:
#        api-v3-mch-key: 1213321
