server:
  servlet:
    context-path: /api

spring:
  application:
    name: demo
  redis:
    database: 8
    host: 192.168.50.202
    password: PenglaiCache
    redisson:
      config: classpath:redisson.yml
#wx:
#  pay:
#    service:
#      provider:
#        api-v3-mch-key: 1213321
