server:
  servlet:
    context-path: /api

spring:
  application:
    name: demo
  redis:
    database: 8
    host: 192.168.50.202
    password: PenglaiCache
    redisson:
      config: classpath:redisson.yml
  rabbitmq:
    host: 172.16.6.55
    port: 5672
    username: admin
    password: admin
    virtual-host: /
#wx:
#  pay:
#    service:
#      provider:
#        api-v3-mch-key: 1213321
